[package]
name = "intuicio-nodes"
version = "0.51.0"
edition = "2024"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
description = "Node Graph module for Intuicio scripting platform"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/intuicio"
repository = "https://github.com/PsichiX/intuicio"
documentation = "https://docs.rs/intuicio-nodes"
readme = "../../README.md"

[dependencies]
intuicio-core = { version = "0.51", path = "../core" }
serde = { version = "1", features = ["derive", "rc"] }
typid = "1"
rstar = "0.12"
serde-intermediate = "1.5"

[dev-dependencies]
serde_json = "1"
